{{- if .Values.ingress.public.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "phvalheim.fullname" . }}-public
  labels:
    {{- include "phvalheim.labels" . | nindent 4 }}
  {{- with .Values.ingress.public.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.public.className }}
  ingressClassName: {{ .Values.ingress.public.className }}
  {{- end }}
  {{- if .Values.ingress.public.tls }}
  tls:
    {{- range .Values.ingress.public.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.public.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "phvalheim.fullname" $ }}-public
                port:
                  number: {{ $.Values.service.public.port }}
          {{- end }}
    {{- end }}
{{- end }}
---
{{- if .Values.ingress.admin.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "phvalheim.fullname" . }}-admin
  labels:
    {{- include "phvalheim.labels" . | nindent 4 }}
  {{- with .Values.ingress.admin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.admin.className }}
  ingressClassName: {{ .Values.ingress.admin.className }}
  {{- end }}
  {{- if .Values.ingress.admin.tls }}
  tls:
    {{- range .Values.ingress.admin.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.admin.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "phvalheim.fullname" $ }}-admin
                port:
                  number: {{ $.Values.service.admin.port }}
          {{- end }}
    {{- end }}
{{- end }}
