{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "phvalheim.fullname" . }}-data
  labels:
    {{- include "phvalheim.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if and .Values.persistence.backups.enabled (not .Values.persistence.backups.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "phvalheim.fullname" . }}-backups
  labels:
    {{- include "phvalheim.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.backups.accessMode }}
  {{- if .Values.persistence.backups.storageClass }}
  storageClassName: {{ .Values.persistence.backups.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
{{- end }}
