apiVersion: v1
kind: Service
metadata:
  name: {{ include "phvalheim.fullname" . }}-public
  labels:
    {{- include "phvalheim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.public.type }}
  ports:
    - port: {{ .Values.service.public.port }}
      targetPort: public
      protocol: TCP
      name: http
  selector:
    {{- include "phvalheim.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "phvalheim.fullname" . }}-admin
  labels:
    {{- include "phvalheim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: admin
      protocol: TCP
      name: http
  selector:
    {{- include "phvalheim.selectorLabels" . | nindent 4 }}
